### ISSUE TITLE
Cache entry with start date

### ISSUE THREAD

**Issue by Floriswijgergangs** [supercool/Cache-Monster#3]
Hi, 

The plugin is only working on save of an entry. 
When saving an entry with an entry date in the future, the post will be shown on that specific date. 
The plugin needs to clear that cache on the entry date, because things like the entry url / link will be commented out in the frontend. 

Not sure if this is an issue or an feature request. 
If you need more information, let me know!

Thanks for the plugin!

**Comment by joshangell** [comment]
Thanks, this is a tricky one and mainly due to the fact that the native cache tag doesn't have any events that get fired. If there was an event that got fired just before a set of caches were cleared then I could use that instead of `onElementSave`. As it is, there isn't.

The only workaround I have in mind right now is to set up a cron job that re-saves all elements every night or something.

Sorry I can't be of more help, I'll leave this open though as I think a feature request for some more events in Craft would be a good idea.

**Comment by joshangell** [comment]
Just to update you that this will be coming in v2 - which is in development in the [v2 branch](https://github.com/supercool/Cache-Monster/tree/v2). Check out the roadmap there for how the new setup will work.

**Comment by joshangell** [comment]
Ok, nothing in the new v2 will help with this - but I do have in mind a plugin that handles just this problem. It would re-save at a given time - e.g. when it is supposed to go live or expire. I'll update here if it ever makes it into the wild.
